---
deployment:
  tasks:
    - export DEPLOYPATH=/home/source12/snatch.sourcecode9.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH
    - /bin/cp -R app.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R *.png $DEPLOYPATH
